default:
  region: us-east-1
  output_dir: ./output

alb:
  bucket: my-alb-logs-bucket
  prefix: AWSLogs/123456789012/elasticloadbalancing/us-east-1/app/my-alb/

cf:
  bucket: my-cf-logs-bucket
  prefix: mydistribution-logs/
